# CodeRabbit Configuration
# https://docs.coderabbit.ai/

# CodeRabbit works via the GitHub App - no workflow file needed
# Just install the app at: https://github.com/apps/coderabbitai

reviews:
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - packages/**/*.ts
    - packages/**/*.tsx
    - supabase/migrations/**/*.sql
    - '!**/*.test.ts'
    - '!**/__tests__/**'
    - '!node_modules/**'
    - '!dist/**'
    - '!build/**'
  path_instructions:
    - path: 'packages/bot/src/commands/**/*.ts'
      instructions: 'Check that new command features have corresponding tests in __tests__/commands/'
    - path: 'packages/bot/src/providers/**/*.ts'
      instructions: 'Check that new provider features have corresponding tests and proper error handling'
    - path: 'packages/bot/src/security/**/*.ts'
      instructions: 'Review for input validation, auth checks, and ensure tests cover security scenarios'
    - path: 'supabase/migrations/**/*.sql'
      instructions: 'Ensure SQL migrations use IF NOT EXISTS and are reversible'
    - path: 'packages/**/*.ts'
      instructions: 'Check for proper type annotations and no any types'
    - path: 'packages/bot/src/database/**/*.ts'
      instructions: 'Review for SQL injection prevention, proper parameterized queries, and input validation'
    - path: 'packages/bot/src/services/cost-aggregator.ts'
      instructions: 'Ensure cost calculations are correct and properly logged'
    - path: 'packages/bot/src/database/admin-adapter.ts'
      instructions: 'Validate cost tracking logic, proper token counting, and accurate price calculations'

chat:
  auto_reply: true
