export type SlurDetectionStage = 'input' | 'assistant_output';

export interface SlurDetectionResult {
  lexicalMatches: string[];
  evasionMatches: string[];
  initialismMatches: string[];
}

const BLOCKED_SLUR_TOKENS = [
  'faggot',
  'nigger',
  'kike',
  'chink',
  'spic',
  'gook',
  'wetback',
  'tranny',
  'dyke',
  'lesbo',
  'coon',
  'darkie',
  'jigaboo',
  'porchmonkey',
  'retard',
  'retarded',
  'mongoloid',
  'beaner',
  'raghead',
  'towelhead',
  'sandnigger',
  'sandmonkey',
  'slanteye',
  'zipperhead',
  'zippercunt',
  'chinaman',
  'dothead'
] as const;

// These common shortened spellings are treated as slur evasions when they are
// generated by the assistant, separated with punctuation, or derived from an
// acronym request. Keeping them separate avoids treating every matching plain
// user token as a direct lexical slur without considering context.
const BLOCKED_SLUR_VARIANTS = ['nigga', 'niga', 'fag'] as const;

const ALL_BLOCKED_FORMS = [...BLOCKED_SLUR_TOKENS, ...BLOCKED_SLUR_VARIANTS];
const BLOCKED_FORM_SET = new Set<string>(ALL_BLOCKED_FORMS);
const MIN_INITIALISM_LENGTH = Math.min(...ALL_BLOCKED_FORMS.map(token => token.length));
const MAX_INITIALISM_LENGTH = Math.max(...ALL_BLOCKED_FORMS.map(token => token.length));

const LEETSPEAK_CHAR_MAP: Record<string, string> = {
  '0': 'o',
  '1': 'i',
  '2': 'z',
  '3': 'e',
  '4': 'a',
  '5': 's',
  '6': 'g',
  '7': 't',
  '8': 'b',
  '9': 'g',
  '@': 'a',
  $: 's',
  '!': 'i',
  '|': 'i',
  '+': 't'
};

// NFKD does not collapse cross-script characters that are visually confusable
// with Latin letters, so normalize the forms most useful for safety evasion.
const UNICODE_CONFUSABLE_CHAR_MAP: Record<string, string> = {
  '\u0410': 'A',
  '\u0430': 'a',
  '\u0412': 'B',
  '\u0432': 'b',
  '\u0421': 'C',
  '\u0441': 'c',
  '\u0415': 'E',
  '\u0435': 'e',
  '\u0406': 'I',
  '\u0456': 'i',
  '\u0408': 'J',
  '\u0458': 'j',
  '\u041A': 'K',
  '\u043A': 'k',
  '\u041C': 'M',
  '\u043C': 'm',
  '\u041D': 'H',
  '\u043D': 'h',
  '\u041E': 'O',
  '\u043E': 'o',
  '\u0420': 'P',
  '\u0440': 'p',
  '\u0405': 'S',
  '\u0455': 's',
  '\u0422': 'T',
  '\u0442': 't',
  '\u0425': 'X',
  '\u0445': 'x',
  '\u0423': 'Y',
  '\u0443': 'y',
  '\u04CF': 'l',
  '\u0391': 'A',
  '\u03B1': 'a',
  '\u0392': 'B',
  '\u03B2': 'b',
  '\u03F9': 'C',
  '\u03F2': 'c',
  '\u0395': 'E',
  '\u03B5': 'e',
  '\u0397': 'H',
  '\u03B7': 'h',
  '\u0399': 'I',
  '\u03B9': 'i',
  '\u039A': 'K',
  '\u03BA': 'k',
  '\u039C': 'M',
  '\u03BC': 'm',
  '\u039D': 'N',
  '\u03BD': 'v',
  '\u039F': 'O',
  '\u03BF': 'o',
  '\u03A1': 'P',
  '\u03C1': 'p',
  '\u03A4': 'T',
  '\u03C4': 't',
  '\u03A7': 'X',
  '\u03C7': 'x',
  '\u03A5': 'Y',
  '\u03C5': 'y'
};

const INITIALISM_INTENT_PATTERN =
  /\b(?:abbreviation|acronym|initialism|initials?|first\s+letters?|first\s+letter\s+of\s+each|separate(?:\s+the)?\s+letters?|letters?\s+with\s+periods?|acrostic|(?:sorry\s+)?i\s+meant)\b/i;

const OUTPUT_MASK_CHARACTER_CLASS: Record<string, string> = {
  a: '[aаα4@]',
  b: '[bвβ8]',
  c: '[cсϲ]',
  d: '[dԁ]',
  e: '[eеε3]',
  f: 'f',
  g: '[g69]',
  h: '[hһηн]',
  i: '[iіι1!|]',
  j: '[jј]',
  k: '[kκк]',
  l: '[lӏ1!|]',
  m: '[mмμ]',
  n: '[nηн]',
  o: '[oоο0]',
  p: '[pрρ]',
  q: 'q',
  r: 'r',
  s: '[sѕ5$]',
  t: '[tтτ7+]',
  u: '[uυ]',
  v: '[vν]',
  w: 'w',
  x: '[xхχ]',
  y: '[yуυ]',
  z: '[z2]'
};

function unique(values: string[]): string[] {
  return Array.from(new Set(values));
}

export function normalizeSafetyCharacters(content: string): string {
  return content
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[\u200B-\u200D\u2060\uFEFF]/g, '')
    .split('')
    .map(character => {
      const code = character.codePointAt(0);
      if (!code) return character;

      if (code >= 0xff10 && code <= 0xff19) return String.fromCharCode(code - 0xff10 + 0x30);
      if (code >= 0xff21 && code <= 0xff3a) return String.fromCharCode(code - 0xff21 + 0x41);
      if (code >= 0xff41 && code <= 0xff5a) return String.fromCharCode(code - 0xff41 + 0x61);
      if (code >= 0x24b6 && code <= 0x24cf) return String.fromCharCode(code - 0x24b6 + 0x41);
      if (code >= 0x24d0 && code <= 0x24e9) return String.fromCharCode(code - 0x24d0 + 0x61);

      return UNICODE_CONFUSABLE_CHAR_MAP[character] || character;
    })
    .join('');
}

export function normalizeSafetyToken(content: string): string {
  return normalizeSafetyText(content).replace(/[^a-z]/g, '');
}

export function normalizeSafetyText(content: string): string {
  return normalizeSafetyCharacters(content)
    .toLowerCase()
    .split('')
    .map(character => LEETSPEAK_CHAR_MAP[character] || character)
    .join('');
}

function matchesInflectedBlockedForm(token: string, forms: ReadonlySet<string>): boolean {
  if (forms.has(token)) return true;
  if (token.endsWith('s') && forms.has(token.slice(0, -1))) return true;
  if (token.endsWith('ies') && forms.has(`${token.slice(0, -3)}y`)) return true;
  return false;
}

function extractVisibleTokens(content: string): string[] {
  return normalizeSafetyCharacters(content)
    .toLowerCase()
    .split(/\s+/)
    .map(token => token.replace(/^[^a-z0-9@!|+$]+|[^a-z0-9@!|+$]+$/g, ''))
    .filter(Boolean);
}

function collectSeparatedMatches(content: string): string[] {
  const normalized = normalizeSafetyCharacters(content);
  return ALL_BLOCKED_FORMS.filter(form => {
    const separator = '[\\W_\\u200B-\\u200D\\u2060\\uFEFF]+';
    const pattern = new RegExp(
      `(?:^|\\b)${form.split('').join(separator)}(?:${separator}s)?(?:\\b|$)`,
      'i'
    );
    return pattern.test(normalized);
  });
}

function collectInitialismMatches(content: string): string[] {
  if (!INITIALISM_INTENT_PATTERN.test(content)) return [];

  const words = normalizeSafetyCharacters(content)
    .toLowerCase()
    .match(/[a-z]+/g);
  if (!words) return [];

  const matches: string[] = [];
  for (let start = 0; start < words.length; start += 1) {
    let initialism = '';
    for (
      let index = start;
      index < words.length && index - start < MAX_INITIALISM_LENGTH;
      index += 1
    ) {
      initialism += words[index]?.[0] || '';
      if (initialism.length >= MIN_INITIALISM_LENGTH && BLOCKED_FORM_SET.has(initialism)) {
        matches.push(initialism);
      }
    }
  }

  return unique(matches);
}

export function detectSlurSafety(content: string, stage: SlurDetectionStage): SlurDetectionResult {
  const canonicalForms = new Set<string>(BLOCKED_SLUR_TOKENS);
  const allForms = new Set<string>(ALL_BLOCKED_FORMS);
  const visibleTokens = extractVisibleTokens(content);
  const lexicalMatches = visibleTokens
    .map(token => normalizeSafetyToken(token))
    .filter(token =>
      matchesInflectedBlockedForm(token, stage === 'assistant_output' ? allForms : canonicalForms)
    );
  const separatedMatches = collectSeparatedMatches(content);
  const normalizedEvasions = visibleTokens
    .map(token => ({
      normalized: normalizeSafetyToken(token),
      visible: normalizeSafetyCharacters(token)
        .toLowerCase()
        .replace(/[^a-z]/g, '')
    }))
    .filter(
      token =>
        matchesInflectedBlockedForm(token.normalized, allForms) &&
        token.visible !== token.normalized
    )
    .map(token => token.normalized);

  return {
    lexicalMatches: unique([...lexicalMatches, ...separatedMatches]),
    evasionMatches: unique([...separatedMatches, ...normalizedEvasions]),
    initialismMatches: collectInitialismMatches(content)
  };
}

export function hasPlainCanonicalSlur(content: string): boolean {
  return detectSlurSafety(content, 'input').lexicalMatches.length > 0;
}

export interface MaskedAssistantSlurResult {
  content: string;
  changed: boolean;
  matchedForms: string[];
  categories: string[];
  fallbackUsed: boolean;
}

export function maskAssistantSlurs(content: string): MaskedAssistantSlurResult {
  const detection = detectSlurSafety(content, 'assistant_output');
  const matchedForms = unique([
    ...detection.lexicalMatches,
    ...detection.evasionMatches,
    ...detection.initialismMatches
  ]);
  if (matchedForms.length === 0) {
    return { content, changed: false, matchedForms: [], categories: [], fallbackUsed: false };
  }

  const categories = unique([
    ...(detection.lexicalMatches.length > 0 ? ['hate/slur_usage'] : []),
    ...(detection.evasionMatches.length > 0 ? ['hate/slur_evasion'] : []),
    ...(detection.initialismMatches.length > 0 ? ['hate/slur_acronym_evasion'] : [])
  ]);

  let masked = content;
  const separator = '[\\s._\\-–—*~`\\u200B-\\u200D\\u2060\\uFEFF]*';
  for (const form of ALL_BLOCKED_FORMS) {
    const body = form
      .split('')
      .map(character => OUTPUT_MASK_CHARACTER_CLASS[character] || character)
      .join(separator);
    const pattern = new RegExp(`(^|[^\\p{L}\\p{N}])(?:${body})(?:s)?(?=$|[^\\p{L}\\p{N}])`, 'giu');
    masked = masked.replace(pattern, (_match, prefix: string) => `${prefix}[slur removed]`);
  }

  const remaining = detectSlurSafety(masked, 'assistant_output');
  if (
    remaining.lexicalMatches.length > 0 ||
    remaining.evasionMatches.length > 0 ||
    remaining.initialismMatches.length > 0
  ) {
    return {
      content:
        'I’m not repeating that term. I can explain the meaning or context without spelling it.',
      changed: true,
      matchedForms,
      categories,
      fallbackUsed: true
    };
  }

  return {
    content: masked,
    changed: masked !== content,
    matchedForms,
    categories,
    fallbackUsed: false
  };
}
